#!/usr/bin/env python3
"""Flatten a skill for harnesses that paste instead of load (3 output styles).

INPUTS:  argv[1] = skill directory (contains SKILL.md). Flags:
           --style flat|rules|agents   (default flat)
           --out PATH      output file (default: <skill>/../<name>.<style>.md)
           --refs all|none comma-list  (default all: inline references/ files)
OUTPUTS: one markdown file:
           flat   - self-contained doc for system-prompt/first-message pasting:
                    frontmatter stripped, references inlined as sections,
                    relative links to inlined files converted to section
                    pointers; sibling links noted as suite references.
           rules  - flat body wrapped in a generic rules-file header
                    (Cursor/Windsurf style; frontmatter conventions vary -
                    verify current docs; marked in-file).
           agents - AGENTS.md fragment: pointer block telling an agent which
                    file to read when (no inlining beyond the body).
         Also validates frontmatter + internal link integrity while building
         (fails before writing a broken export).
EXIT:    0 = export written | 1 = validation/domain failure | 2 = bad input
EDGE:    skill with no references/ works (inlining skipped); unknown reference
         names error; re-run overwrites the output; huge references inlined
         verbatim (file size grows accordingly).
NON-GOALS: does not inline SIBLING skills (the flatten test covers the single
         skill; sibling pointers are annotated as suite references); does not
         package .skill zips; does not translate scripts (exports reference
         them by path).
"""
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
try:
    from validate_suite import parse_frontmatter, check_links
except ImportError:
    parse_frontmatter = None

RULES_HEADER = """---
description: %(name)s guidance from the pcb-skills suite
alwaysApply: true
---

<!-- Generated by export_for_harness.py --style rules. Rules-file frontmatter
conventions vary by harness version - verify against your tool's docs. -->
"""

AGENTS_HEADER = """## Skill: %(name)s

Read `%(rel)s/SKILL.md` (and the references it points to) whenever: %(trigger)s

"""


def inline_references(body, refs_dir, chosen):
    """Inline chosen reference files; rewrite links to them as section notes."""
    files = []
    if os.path.isdir(refs_dir):
        for f in sorted(os.listdir(refs_dir)):
            if f.endswith(".md"):
                files.append(f)
    if chosen == "none":
        files = []
    elif chosen != "all":
        want = [c.strip() for c in chosen.split(",") if c.strip()]
        unknown = [w for w in want if w not in files]
        if unknown:
            return None, "unknown references requested: %s (have %s)" % (
                unknown, files)
        files = [f for f in files if f in want]
    out = [body, "\n\n---\n\n<!-- Inlined references (from references/) -->\n"]
    for f in files:
        text = open(os.path.join(refs_dir, f), encoding="utf-8").read()
        anchor = f.replace("/", "-").replace(".", "-")
        out.append("\n\n<!-- ===== BEGIN references/%s ===== -->\n\n" % f)
        out.append(text)
        out.append("\n\n<!-- ===== END references/%s ===== -->\n" % f)
        body_link = "references/%s" % f
        # link rewrite happens on the joined body below
    joined = "".join(out)
    for f in files:
        joined = joined.replace("(references/%s)" % f,
                                "(inlined section: references/%s)" % f)
    joined = re.sub(r"\]\(\.\./(pcb-[a-z-]+)/SKILL\.md\)",
                    r"](sibling skill \1 - see the pcb-skills suite)", joined)
    return joined, None


def main(argv):
    style = "flat"
    out = None
    refs = "all"
    pos = []
    i = 1
    while i < len(argv):
        a = argv[i]
        if a in ("--style", "--out", "--refs"):
            if i + 1 >= len(argv):
                print("ERROR: %s needs a value" % a)
                return 2
            if a == "--style":
                style = argv[i + 1]
            elif a == "--out":
                out = argv[i + 1]
            else:
                refs = argv[i + 1]
            i += 2
            continue
        if a in ("-h", "--help"):
            print(__doc__)
            return 0
        pos.append(a)
        i += 1
    if style not in ("flat", "rules", "agents"):
        print("ERROR: --style must be flat|rules|agents")
        return 2
    if not pos or not os.path.isdir(pos[0]):
        print("ERROR: pass the skill directory (contains SKILL.md)")
        return 2
    skill = os.path.abspath(pos[0])
    sk = os.path.join(skill, "SKILL.md")
    if not os.path.isfile(sk):
        print("ERROR: no SKILL.md in %s" % skill)
        return 2
    if parse_frontmatter is None:
        print("ERROR: validate_suite.py import failed (keep both in scripts/)")
        return 2
    name, desc, err = parse_frontmatter(sk)
    if err or not name or not desc:
        print("ERROR: frontmatter invalid: %s" % (err or "name/description"))
        return 1
    bad = check_links(sk, os.path.dirname(skill))
    if bad:
        for b in bad:
            print("ERROR: %s" % b)
        return 1
    body = open(sk, encoding="utf-8").read()
    body = re.sub(r"^---\n.*?\n---\n", "", body, count=1, flags=re.DOTALL)
    if style == "agents":
        rel = os.path.relpath(skill, os.path.dirname(skill))
        frag = AGENTS_HEADER % {"name": name, "rel": rel, "trigger": desc}
        frag += "Guide body (follow when the file above is unavailable):\n" + body
        text = frag
    else:
        text, ierr = inline_references(body, os.path.join(skill, "references"),
                                       refs)
        if text is None:
            print("ERROR: %s" % ierr)
            return 1
        if style == "rules":
            text = (RULES_HEADER % {"name": name}) + text
        else:
            text = ("<!-- Flattened export of %s (pcb-skills suite). "
                    "Self-contained by design. -->\n" % name) + text
    if not out:
        out = os.path.join(os.path.dirname(skill),
                           "%s.%s.md" % (name, style))
    with open(out, "w", encoding="utf-8") as fh:
        fh.write(text)
    print("export_for_harness: wrote %s (%d bytes, style=%s, refs=%s)"
          % (out, len(text), style, refs))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
